### ISSUE TITLE
Issue with "create services" field

### ISSUE THREAD

**Issue by admonstrator** [thomas-krenn/TKmon#1]
Hi there,

we are using TKmon 2.1.1 and encountered a strange issue with the "create a new service" field. 
If I am "too fast" while typing the search-field for services will stop working and the following error message will appear:

`AjaxForm.js:230 Uncaught TypeError: $(...).serializeJSON is not a function
    at init.$.fn.serializeJson (AjaxForm.js:230)
    at HTMLFormElement.<anonymous> (Editor.js:125)
    at HTMLFormElement.dispatch (jquery-1.10.2.min.js:5)
    at HTMLFormElement.v.handle (jquery-1.10.2.min.js:5)
$.fn.serializeJson @ AjaxForm.js:230
(anonymous) @ Editor.js:125
dispatch @ jquery-1.10.2.min.js:5
v.handle @ jquery-1.10.2.min.js:5`

After this issue appeares it is gone for a while but it will show up again after a few tries.
I can not reproduce it properly but maybe you can have a look into this issue?

**Comment by tk-wfischer** [comment]
Hi and thank you for your report.

Until now I have not encountered this issue. Could you maybe take a screenshot when you hit this issue and post it?

Meanwhile we will try to reproduce this issue and keep you updated once we have news on that.

**Comment by admonstrator** [comment]
Hi,

I was able to create an screencast while the issue appears.
It seems to be an problem with the jquery include. 

If I reload the "edit services" page sometimes the jquery library will not be loaded correctly.
You can download the screencast here: -deleted-

**Comment by tk-wfischer** [comment]
Thank you for your recorded screencast. I was able to reproduce this issue with Chromium on Ubuntu 14.04 (using Chromium version 53.0.2785.143-0ubuntu0.14.04.1.1145).

Each time, the "Add" button is clicked here, the number of errors ("9" in this screenshot) raises by 1:

![screenshot-tkmon-chromium](https://cloud.githubusercontent.com/assets/10231856/21978703/08588754-dbdc-11e6-8404-44916690b374.png)

Firefox version 50.0.1 (also on Ubuntu 14.04) does not show this issue. So in the meantime I can only suggest using Firefox as a workaround.

We will look into this issue and how we could fix it and keep you updated.

**Comment by admonstrator** [comment]
Thanks for your fast reply!
Due to the fact that the issue does not appears always it is fine for me at this time.

Looking forward to a bugfix.

**Comment by tniedermeier** [comment]
Hi,
thanks for your report also from my side.
There were a few occasions, where I also encountered exactly these problems.
I've already opened a issue to keep this in mind for our next release: https://git.netways.org/thomas-krenn/tkmon-web/issues/4
At the moment, we can't say when a new version of TKmon will be released, but this issue will be fixed thereby.

**Comment by tniedermeier** [comment]
Issue is fixed in the new TKmon 2.2 release.
