### ISSUE TITLE
Fix generic SNMPv2 check

### ISSUE THREAD

**Issue by tk-wfischer** [thomas-krenn/TKmon#2]
When I want to add an SNMP service check, and I type "generic", I only see two entries which refer to SNMPv3:
 ![tkmon-screenshot](https://cloud.githubusercontent.com/assets/10231856/23988585/23b72dc6-0a2f-11e7-863c-030a6381755b.png)

TODO: fix it, so that a generic SNMPv2 check works.

**Comment by tniedermeier** [comment]
Fixed with the new TKmon 2.2 release, if you type oid or custom, both checks are now show.
