### ISSUE TITLE
Mail notification is not working

### ISSUE THREAD

**Issue by reqTibi** [thomas-krenn/TKmon#3]
Hallo,
i use TKMON v2.0.0 for monitoring. I configured the mail setting already correct and sending a test mail is working fine, but icinga is not sending the mail. In the notifications i see that a mail was initiated, but it seems that the mail is not sended. Do you have an idea how to get it working?

Cheers Tiberius

**Comment by tniedermeier** [comment]
Hi Tiberius,

thanks for your message and also thanks for utilizing TKmon. Did you configure a contact with a valid e-mail address in TKmon?
You can configure them in the left menu "CONTACTS" below the "HOSTS" button.
The icinga notification mechanism sends mails only to e-mail addresses configured in the contacts.
The test mail works independent from the contacts.

I hope i could help you with your issue.

Cheers, Thomas

**Comment by tk-wfischer** [comment]
Hi Tiberius,

does it now work for you after configuring the "CONTACTS"?
In case you still have issues, we are happy to help.

Best regards,
Werner
